### ISSUE TITLE
按攻击按钮后没反应

### ISSUE THREAD

**Issue by breezelog** [JasonYANG170/YANG-SMS#12]
如题，按了攻击按钮后弹出了命令框，但是没有任何输出，手机也没有受到短信。python环境是有的。

PS：开梯子后输入密钥会显示错误，关闭梯子再输入同样密钥就能进程序了；是否有电报群或社区什么的能和其他人交流呢？

**Comment by JasonYANG170** [comment]
输入攻击信息后点击下方保存按键后再点击攻击按钮。无需使用梯子，点击配置代理按钮直接使用代理程序即可

**Comment by JasonYANG170** [comment]
2项问题已在V6.1.0版本中解决，请更新版本
