### ISSUE TITLE
请问为什么输入token69763后显示密码错误？谢谢

### ISSUE THREAD

**Issue by jiajiao272727** [JasonYANG170/YANG-SMS#13]
请问是修改了新的token吗？感谢

**Comment by Deep-Liang** [comment]
我也遇到此问题

**Comment by JasonYANG170** [comment]
我暂未发现相关问题，应该是您的网络无法连接至服务器
解决办法：
_1.请不要使用VPN或系统代理。_
_2.应对相关问题我**发布了V6.0.3版本**，更换了新的密钥服务器，您可以下载V6.0.3版本_
[v6.0.3.zip](https://github.com/JasonYANG170/YANG-SMS/files/10912071/v6.0.3.zip)

**Comment by JasonYANG170** [comment]
发布重要安全更新，请更新至V6.1.0版本，忽略6.0.3版本

**Comment by jiajiao272727** [comment]
想问一下是只有国内能用吗？6.0.3和6.1.0都是只能打开一次，进入到控制台界面点击运行之后出现了黑色的窗口，但没有任何反应，然后软件显示无响应。关闭程序再次打开就无法进入控制台了，显示秘钥错误请与开发者联系。

**Comment by JasonYANG170** [comment]
是的，因为所有的短信接口都是国内接口，如果使用了国外vpn或者代理程序会导致无法连接到国内接口，所以建议您使用国内代理或者vpn来保护您的隐私

**Comment by jiajiao272727** [comment]
原来如此，感谢耐心解答~
