### ISSUE TITLE
实际收到的短信太少

### ISSUE THREAD

**Issue by Skipalong543** [JasonYANG170/YANG-SMS#15]
一次下来只能收到五六条短信，而且就算添加了代理后，感觉速度还是比较慢，有没有什么方法或者哪位大佬在维护接口啊

**Comment by JasonYANG170** [comment]
现在大部分接口使用图形验证码阻止机器人自动发送，类似措施暂时无解，您可以在电话攻击功能中手动发送攻击信息至营销平台客服，这也是目前存活率最高的办法

**Comment by CN957** [comment]
> 现在大部分使用验证码阻止机器人，类似自动机器人机器人自动无解，您无解，您无解无解暂时暂时暂时无解措施暂时在可以在在在在在在在在在电话电话电话攻击攻击攻击功能功能中手动中手动发送攻击攻击信息平台

凑字数的神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神神
