### ISSUE TITLE
下载后  右键安装没有反应

### ISSUE THREAD

**Issue by Striver39** [JasonYANG170/YANG-SMS#17]
下载后  右键安装没有反应
![image](https://user-images.githubusercontent.com/98213104/230717354-ba26f331-5c58-4b92-90f7-816fe1a68ab0.png)

**Comment by Striver39** [comment]
![image](https://user-images.githubusercontent.com/98213104/230719302-11f22a16-9127-4b87-9aec-0ec591c70fea.png)
没有反应  应用死机

**Comment by Striver39** [comment]
![image](https://user-images.githubusercontent.com/98213104/230719394-9a75bc08-eab3-4010-86ce-1d621eefa785.png)
无反应 死机

**Comment by JasonYANG170** [comment]
没有遇到过相关问题，可能是Python环境配置存在问题，我稍后研究一下，您也可在其他电脑尝试

**Comment by Striver39** [comment]
好的大佬，就是点击攻击之后没有反应，要么就是卡死了，我python安装的是3.10版本的，也加入全局环境变量了


&nbsp;&nbsp;&nbsp;&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonYANG170/YANG-SMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 晚上9:02
***@***.***&gt;;
抄送:&nbsp;"    ***@***.******@***.***&gt;;
主题:&nbsp;Re: [JasonYANG170/YANG-SMS] 下载后  右键安装没有反应 (Issue #17)





 
没有遇到过相关问题，可能是Python环境配置存在问题，我稍后研究一下，您也可在其他电脑尝试

**Comment by JasonYANG170** [comment]
已发布新版本，虚拟机测试并未发现相关问题，请确认您使用的是完整版而非精简版windows系统，并且为64位系统。
