### ISSUE TITLE
输入token后点击登录没有反应。。。

### ISSUE THREAD

**Issue by Fantasy404** [JasonYANG170/YANG-SMS#18]

**Comment by JasonYANG170** [comment]
请确保您连接的中国网络，如使用了代理程序，请使用中国节点。（使用中国节点一样能保证您的隐私安全）

**Comment by JasonYANG170** [comment]
程序的服务器在中国，因为没有visa支付方式所以暂时未开通国外服务器。后续我会把服务器转往国外

**Comment by JasonYANG170** [comment]
已发布新版本，虚拟机验证并无相关问题，您可以下载新版本体验🥰
