### ISSUE TITLE
安装完成后双击快捷方式出现错误

### ISSUE THREAD

**Issue by superYuezhang** [JasonYANG170/YANG-SMS#22]
![QQ截图20230505195949](https://user-images.githubusercontent.com/47021399/236453249-5e7fd717-a912-48a8-87e5-88cad0507848.png)
我尝试了6.8.0和6.7.0版本均出现相同的问题，VPN已关闭

**Comment by superYuezhang** [comment]
安装目录为D盘，路径无中文和空格

**Comment by JasonYANG170** [comment]
已收到，请确认您是64位处理器，我会在虚拟机检测此问题

**Comment by superYuezhang** [comment]
> 已收到，请确认您是64位系统，我会在虚拟机检测此问题

对的，64位win11机器

**Comment by JasonYANG170** [comment]
是否还有其他dll缺失，请告诉我，我会尽快添加这些dll到软件中，这应该是WIN11更新导致的，此前并没有相关错误报告。

**Comment by superYuezhang** [comment]
> 是否还有其他dll缺失，请告诉我，我会尽快添加这些dll到软件中，这应该是WIN11更新导致的，此前并没有相关错误报告。

暂无，只提示缺少这一个dll文件

**Comment by JasonYANG170** [comment]
已发布V6.8.2请重新尝试安装，
如果问题依旧存在请在V6.8.2更新日志下方下载缺失dll并安装在C:\Windows\SysWOW64或C:\Windows\System32中，感谢您的反馈。
