### ISSUE TITLE
releases里貌似没有YANG SMS.zip

### ISSUE THREAD

**Issue by chinajc** [JasonYANG170/YANG-SMS#5]
releases只有一个exe和两个一样的压缩包压缩包里是.md文件

**Comment by JasonYANG170** [comment]
您可以下载msi或者exe文件的安装包，zip文件是初代版本，现在已经通过exe或msi文件代替

**Comment by chinajc** [comment]
不好使啊老哥安装到别的盘还是运行不了报好几个找不到代码无法继续运行。😭😭😭

**Comment by JasonYANG170** [comment]
您是否有安装python环境，请尝试在微软商城下载python后运行，这是一个独立程序，不需要您使用编译器运行。

**Comment by JasonYANG170** [comment]
安装完成后您的桌面会出现本程序的快捷方式，点击即可使用

**Comment by chinajc** [comment]
装了，python3.11.2

**Comment by JasonYANG170** [comment]
可否提供下报错内容

**Comment by chinajc** [comment]
桌面有快捷方式一运行就报错“找不到mfc140d.dll，无法继续执行代码。重新安装可能会解决此问题” 重安了也不好使。😭😭😭

**Comment by chinajc** [comment]
报错顺序是 找不到mfc140d.dll
找不到VCRUNTIME140_1D.dll
找不到VCRUNTIME140D.dll
找不到ucrtbased.dll

**Comment by JasonYANG170** [comment]
感谢，我会在今晚前修复该程序

**Comment by JasonYANG170** [comment]
感谢您的反馈，这是我在编译时错误选择成了Debug模式导致，现在已经发布了5.5.1版本，您可以再次尝试

**Comment by chinajc** [comment]
老哥攻击没反应啊，手机号前用＋区号吗？😀

**Comment by chinajc** [comment]
好了老哥可以正常使用了，刚才没关代理。😄

**Comment by JasonYANG170** [comment]
嗯嗯，如果有新的问题请通知我😊
