### ISSUE TITLE
新版本提示缺少jsoncpp.dll

### ISSUE THREAD

**Issue by Deep-Liang** [JasonYANG170/YANG-SMS#8]
重新安装过也没有用,VC2022已装

**Comment by JasonYANG170** [comment]
收到反馈，我预计在明天修复此问题

**Comment by JasonYANG170** [comment]
已发布V6.0.1版本，您可尝试新版本，因为没有其他设备测试，我很难知道程序兼容情况，如果您遇到新的问题，请再次告诉我，谢谢你🥰
