### ISSUE TITLE
输入密钥失败

### ISSUE THREAD

**Issue by xifanghomo** [JasonYANG170/YANG-SMS#9]
![屏幕截图 2023-03-01 140120](https://user-images.githubusercontent.com/124679912/222057893-6d6f9c7e-5d87-492b-8dc0-644d24419d96.png)
这个怎么破

**Comment by JasonYANG170** [comment]
尚不清楚具体原因，我正在排查，尽快解决，感谢反馈

**Comment by JasonYANG170** [comment]
我在虚拟机尝试并没有发现相关问题，我尝试修改判断机制，并发布了V6.0.1BETA版本，您可下载BETA版本尝试，如在BETA版本中仍然遇到该问题，请反馈给我。感谢🥰

**Comment by JasonYANG170** [comment]
已发布V6.0.1BETA版本
